# SPDX-License-Identifier: GPL-2.0
# Out-of-tree build for ALC269 codec module with ASUS Zenbook Duo UX8406MA
# headset mic pin override (DKMS package: snd-hda-codec-alc269-zenbookduo).

subdir-ccflags-y += -I$(src)/../../common

snd-hda-codec-alc269-y := alc269.o
obj-m := snd-hda-codec-alc269.o
